# Generated by Django 5.1.6 on 2026-03-11 00:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_products', models.PositiveIntegerField(default=10, help_text='Maximum number of active product listings allowed.')),
                ('max_images_per_product', models.PositiveIntegerField(default=3, help_text='Maximum number of images per product listing.')),
                ('max_categories', models.PositiveIntegerField(default=2, help_text='Maximum number of product categories a vendor can list in.')),
                ('can_feature_products', models.BooleanField(default=False, help_text='Can vendor boost/feature individual products?')),
                ('can_use_analytics', models.BooleanField(default=False, help_text='Access to advanced sales and traffic analytics.')),
                ('can_offer_discounts', models.BooleanField(default=False, help_text='Can vendor create discount codes and promotions?')),
                ('can_access_bulk_upload', models.BooleanField(default=False, help_text='Can vendor upload products in bulk via CSV/spreadsheet?')),
                ('can_use_storefront_customization', models.BooleanField(default=False, help_text='Access to custom storefront themes and branding.')),
                ('priority_support', models.BooleanField(default=False, help_text='Vendor gets priority customer support.')),
                ('is_featured_vendor', models.BooleanField(default=False, help_text='Vendor profile is featured/promoted on the platform.')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage on sales (e.g., 10.00 = 10%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('payout_delay_days', models.PositiveIntegerField(default=7, help_text='Number of days before earnings are released to vendor.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is publicly available.')),
                ('is_recommended', models.BooleanField(default=False, help_text='Highlight this plan as recommended.')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PaystackCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_customer', to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PaystackAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=50)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=4)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_reusable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='vendor.vendor')),
                ('paystack_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paystackcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('past_due', 'Past Due')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('trial_end_date', models.DateTimeField(blank=True, help_text='If on a trial, when does it end?', null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment gateway transaction ID (e.g., Paystack reference).', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_subscriptions', to='payments.subscriptionplan')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Subscription',
                'verbose_name_plural': 'Vendor Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_products_count', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usage', to='vendor.vendor')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='payments.vendorsubscription')),
            ],
            options={
                'verbose_name': 'Subscription Usage',
                'verbose_name_plural': 'Subscription Usages',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('initial', 'Initial Subscription'), ('renewal', 'Auto Renewal'), ('upgrade', 'Plan Upgrade'), ('manual', 'Manual Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(max_length=200, unique=True)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vendor.vendor')),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paystackauthorization')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.vendorsubscription')),
            ],
        ),
        migrations.AddIndex(
            model_name='vendorsubscription',
            index=models.Index(fields=['vendor', 'status'], name='payments_ve_vendor__919350_idx'),
        ),
    ]
