# Generated by Django 5.1.6 on 2026-03-16 00:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscriptionplan_paystackcustomer_and_more'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Billing email — may differ from login email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{10,15}$', 'Enter a valid phone number')])),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, help_text='State / region / province', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='GH', help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Billing Profile',
                'verbose_name_plural': 'Billing Profiles',
            },
        ),
        migrations.CreateModel(
            name='MomoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('vodafone', 'Vodafone Cash'), ('airteltigo', 'AirtelTigo Money')], max_length=20)),
                ('phone', models.CharField(help_text='Include country code e.g. +233XXXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{10,15}$', 'Enter a valid phone number')])),
                ('nickname', models.CharField(blank=True, help_text="e.g. 'My MTN number'", max_length=60)),
                ('is_default', models.BooleanField(default=False)),
                ('last_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_accounts', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'MoMo Account',
                'verbose_name_plural': 'MoMo Accounts',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('vendor', 'phone')},
            },
        ),
    ]
