# Generated by Django 5.1.6 on 2026-03-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_billingprofile_momoaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
