# Generated by Django 5.1.6 on 2025-09-25 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_total_alter_orderproduct_amount_and_more'),
        ('payments', '0004_payout'),
        ('vendor', '0008_remove_vendor_vendor_vend_name_0f336b_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payout',
            options={},
        ),
        migrations.AddField(
            model_name='payout',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payout',
            name='product_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payout',
            name='order',
            field=models.ManyToManyField(related_name='payouts', to='order.order'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
