# Generated by Django 5.1.6 on 2026-03-20 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_plan_features_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('confirmation', 'Subscription Confirmation'), ('renewal_success', 'Renewal Success'), ('expiring_soon', 'Expiring Soon Warning'), ('expired', 'Subscription Expired'), ('payment_failed', 'Payment Method Required'), ('cancellation', 'Subscription Cancelled')], max_length=30, unique=True)),
                ('subject', models.CharField(help_text='Email subject line. Supports {{ plan_name }}, {{ vendor_name }}.', max_length=200)),
                ('html_file', models.CharField(blank=True, help_text='Path relative to your templates/ folder, e.g. emails/subscription_confirmation.html', max_length=200)),
                ('text_body', models.TextField(blank=True, help_text='Plain-text fallback. Supports Django template variables: {{ vendor_name }}, {{ plan_name }}, {{ end_date }}, {{ days_left }}, {{ frontend_url }}')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this email type entirely.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_warning_days', models.PositiveIntegerField(default=7, help_text='Send the "expiring soon" email this many days before the subscription ends.', validators=[django.core.validators.MinValueValidator(1)])),
                ('second_warning_days', models.PositiveIntegerField(default=3, help_text='Send a second warning this many days before expiry. Set to 0 to disable.', validators=[django.core.validators.MinValueValidator(1)])),
                ('renewal_advance_days', models.PositiveIntegerField(default=1, help_text='Attempt auto-renewal this many days before the subscription end date.', validators=[django.core.validators.MinValueValidator(1)])),
                ('renewal_max_retries', models.PositiveIntegerField(default=3, help_text='How many times to retry a failed renewal charge (once per day each retry).')),
                ('from_email', models.EmailField(default='noreply@negromart.com', help_text='Sender address for all subscription emails.', max_length=254)),
                ('from_name', models.CharField(default='Negromart', help_text='Sender display name.', max_length=100)),
                ('reply_to', models.EmailField(blank=True, help_text='Reply-to address (optional).', max_length=254)),
                ('support_url', models.URLField(default='https://seller.negromart.com/support/', help_text='Support link shown in emails.')),
                ('frontend_url', models.URLField(default='https://seller.negromart.com', help_text='Base URL for links in emails.')),
                ('run_renewals_hour', models.PositiveIntegerField(default=8, help_text='Hour (0–23) to run the daily renewal task (UTC).')),
                ('run_renewals_minute', models.PositiveIntegerField(default=0, help_text='Minute (0–59) for the renewal task.')),
                ('run_expiry_check_hour', models.PositiveIntegerField(default=9, help_text='Hour to run the expiry warning check (UTC).')),
                ('run_expiry_check_minute', models.PositiveIntegerField(default=0)),
                ('run_expire_old_hour', models.PositiveIntegerField(default=0, help_text='Hour to run the subscription expiration cleanup (UTC).')),
                ('run_expire_old_minute', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Email & Schedule Configuration',
                'verbose_name_plural': 'Email & Schedule Configuration',
            },
        ),
    ]
