# Generated by Django 5.1.6 on 2026-10-07 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_returns_and_delivery_providers'),
        ('payments', '0007_fix_relationship_on_delete'),
        ('vendor', '0009_operations_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_export_reports',
            field=models.BooleanField(default=False, help_text='Vendor can download orders and account statements as CSV.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_team_members',
            field=models.PositiveIntegerField(default=1, help_text="People who can sign in to the store's Seller Centre, owner included (1 = owner only). Pending invitations count towards the limit."),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('success', 'Paid'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('sale', 'Sale'), ('commission', 'Commission'), ('delivery_earning', 'Delivery earning'), ('refund', 'Refund to customer'), ('commission_refund', 'Commission returned'), ('payout', 'Payout'), ('adjustment', 'Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('description', models.CharField(max_length=255)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member, for manual adjustments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.order')),
                ('order_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='order.orderproduct')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.payout')),
                ('return_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.returnrequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='vendor.vendor')),
            ],
            options={
                'verbose_name_plural': 'Ledger entries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['vendor', 'payout', 'available_at'], name='ledger_balance_idx'), models.Index(fields=['vendor', '-created_at'], name='ledger_statement_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('entry_type__in', ('sale', 'commission', 'delivery_earning', 'refund', 'commission_refund'))), fields=('order_product', 'entry_type'), name='uniq_ledger_entry_per_line_and_type')],
            },
        ),
    ]
