# Generated by Django 5.1.6 on 2026-05-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_token_version_usersession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersession',
            new_name='userauths_u_user_id_fecdfa_idx',
            old_name='userauths_u_user_id_idx',
        ),
    ]
