# Generated by Django 5.1.6 on 2025-10-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_user_failed_login_attempts_user_lockout_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
