# Generated by Django 5.1.6 on 2026-05-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_otprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='otp',
            field=models.CharField(max_length=64),
        ),
    ]
