# Generated by Django 5.1.6 on 2026-10-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_otprecord_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otprecord',
            name='purpose',
            field=models.CharField(choices=[('vendor_login', 'Seller login'), ('email_verify', 'Email verification'), ('phone_verify', 'Phone verification')], default='vendor_login', max_length=20),
        ),
        migrations.AddField(
            model_name='otprecord',
            name='target',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('vendor', 'Vendor (legacy, not used for access)'), ('customer', 'Customer'), ('technical', 'Technical'), ('support', 'Support'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='otprecord',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='userauths_o_user_id_4ef8ee_idx'),
        ),
    ]
