# Generated by Django 5.1.6 on 2025-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='homeslider',
            index=models.Index(fields=['is_active'], name='core_homesl_is_acti_704c10_idx'),
        ),
        migrations.AddIndex(
            model_name='homeslider',
            index=models.Index(fields=['order'], name='core_homesl_order_d81598_idx'),
        ),
    ]
