# Generated by Django 5.1.6 on 2025-12-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homeslider_core_homesl_is_acti_704c10_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='banners',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banners',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddIndex(
            model_name='banners',
            index=models.Index(fields=['is_active'], name='core_banner_is_acti_9b7d24_idx'),
        ),
        migrations.AddIndex(
            model_name='banners',
            index=models.Index(fields=['order'], name='core_banner_order_1b3a37_idx'),
        ),
    ]
