# Generated by Django 5.1.6 on 2026-04-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_banners_options_banners_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='content_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Which side of the slide the text block appears on', max_length=6),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='cta_label',
            field=models.CharField(default='Shop now', help_text="Call-to-action button text (e.g. 'Shop now', 'Try Walmart+ now')", max_length=50),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='cta_position',
            field=models.JSONField(blank=True, help_text='Optional: float the "Shop now" button at a specific spot on the image. Enter as JSON with % values, e.g. {"top": "12%", "left": "62%"}. Leave blank to show the button inside the text block.', null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Smaller text shown above the title (e.g. 'Host an epic night in')", max_length=200),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='text_theme',
            field=models.CharField(choices=[('light', 'Light (white text — for dark backgrounds)'), ('dark', 'Dark (black text — for light/white backgrounds)')], default='light', help_text="Use 'dark' when your image has a white/light background", max_length=5),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='deal_type',
            field=models.CharField(choices=[('Daily Deal', 'Daily Deal'), ('Discount', 'Discount'), ('Limited Time', 'Limited Time'), ('Featured', 'Featured'), ('Custom', 'Custom')], default='Custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image_desktop',
            field=models.ImageField(blank=True, help_text='Clean background/product image — NO text baked in. Recommended: 1240×380px', null=True, upload_to='sliders/desktop/'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Clean background/product image — NO text baked in. Recommended: 800×220px', null=True, upload_to='sliders/mobile/'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='link_url',
            field=models.URLField(blank=True, help_text="Destination when user clicks anywhere on the slide or 'Shop now'"),
        ),
    ]
