# Generated by Django 5.1.6 on 2026-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homeslider_content_align_homeslider_cta_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='content_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Which side of the banner the text block appears on', max_length=6),
        ),
        migrations.AddField(
            model_name='banners',
            name='cta_label',
            field=models.CharField(default='Shop now', help_text='Call-to-action button text', max_length=50),
        ),
        migrations.AddField(
            model_name='banners',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Smaller text shown above the title', max_length=200),
        ),
        migrations.AddField(
            model_name='banners',
            name='text_theme',
            field=models.CharField(choices=[('light', 'Light (white text — for dark backgrounds)'), ('dark', 'Dark (black text — for light/white backgrounds)')], default='light', help_text="Use 'dark' when your banner has a white/light background", max_length=5),
        ),
        migrations.AlterField(
            model_name='banners',
            name='deal_type',
            field=models.CharField(choices=[('Daily Deal', 'Daily Deal'), ('Discount', 'Discount'), ('Limited Time', 'Limited Time'), ('Featured', 'Featured'), ('Custom', 'Custom')], default='Custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='banners',
            name='image',
            field=models.ImageField(blank=True, help_text='Clean background/product image — NO text baked in. Recommended: 340×185px', null=True, upload_to='banners/'),
        ),
    ]
