# Generated by Django 5.1.6 on 2026-04-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_banners_content_align_banners_cta_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('eyebrow', models.CharField(blank=True, help_text='Small label above the title', max_length=60)),
                ('link_url', models.CharField(help_text='e.g. /category/shoes or /flash-sales', max_length=300)),
                ('link_text', models.CharField(default='Shop now', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo_cards/')),
                ('card_color', models.CharField(choices=[('white', 'White'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('coral', 'Coral'), ('dark', 'Dark'), ('gray', 'Gray')], default='white', max_length=10)),
                ('badge_text', models.CharField(blank=True, help_text='e.g. Flash Deals, New, Hot', max_length=40)),
                ('badge_color', models.CharField(choices=[('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('dark', 'Dark')], default='yellow', max_length=10)),
                ('is_tall', models.BooleanField(default=False, help_text='Spans 2 rows — use for the big right-column card')),
                ('position', models.PositiveIntegerField(default=0, help_text='Lower = shown first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promo Card',
                'verbose_name_plural': 'Promo Cards',
                'ordering': ['position'],
            },
        ),
    ]
