# Generated by Django 5.1.6 on 2026-05-15 02:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_searchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='searchhistory',
            name='unique_user_query',
        ),
        migrations.RenameIndex(
            model_name='searchhistory',
            new_name='core_search_user_id_2ba9a3_idx',
            old_name='core_search_user_id_idx',
        ),
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together={('user', 'query')},
        ),
    ]
