# Generated by Django 5.1.6 on 2026-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_searchhistory_unique_user_query_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('discord', 'Discord'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('other', 'Other')], max_length=20)),
                ('category', models.CharField(choices=[('community', 'Community Group'), ('social', 'Social Media')], default='social', help_text="'Community' = interactive groups (WhatsApp/Telegram/Discord); 'Social' = follow pages (Instagram/YouTube/etc.)", max_length=10)),
                ('label', models.CharField(help_text="Display name on the card, e.g. 'WhatsApp Channel'", max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, help_text="Short tagline, e.g. 'Get exclusive deals first'", max_length=200)),
                ('member_count', models.CharField(blank=True, help_text="e.g. '12K+ members' — leave blank to hide", max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = shown first within the category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social / Community Link',
                'verbose_name_plural': 'Social / Community Links',
                'ordering': ['category', 'order', 'platform'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='core_social_is_acti_0cda07_idx'), models.Index(fields=['order'], name='core_social_order_003a02_idx')],
            },
        ),
    ]
