# Generated by Django 5.1.6 on 2025-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
        ('product', '0002_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date',)},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='product_pro_status_48d769_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='product_pro_product_3fa8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['views'], name='product_pro_views_b7c72d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['date'], name='product_pro_date_e75398_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor'], name='product_pro_vendor__915e06_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sub_category'], name='product_pro_sub_cat_7642e2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='product_pro_brand_i_5d76ed_idx'),
        ),
    ]
