# Generated by Django 5.1.6 on 2026-02-12 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
        ('product', '0003_alter_product_options_and_more'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_vendor__915e06_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_sub_cat_7642e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_brand_i_5d76ed_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sub_category', 'status', 'id'], name='product_pro_sub_cat_3cd326_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sub_category', 'status', 'price'], name='product_pro_sub_cat_be3e68_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'status'], name='product_pro_brand_i_0ef5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'status'], name='product_pro_vendor__a5bcbf_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'status'], name='product_pro_product_225219_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'rating', 'status'], name='product_pro_product_e4e15a_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product', 'color'], name='product_var_product_250c97_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product', 'size'], name='product_var_product_3284f4_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product', 'color', 'size'], name='product_var_product_974a94_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['color'], name='product_var_color_i_fbf0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['size'], name='product_var_size_id_c5a8e0_idx'),
        ),
    ]
