# Generated by Django 5.1.6 on 2025-09-11 15:39

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_delivery_returns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image of the product', null=True, upload_to=product.models.vendor_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%y'),
        ),
    ]
