# Generated by Django 5.1.6 on 2025-09-13 23:05

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_brand_options_remove_productimages_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=30, max_length=40, prefix='SKU', unique=True),
        ),
    ]
