# Generated by Django 5.1.6 on 2025-09-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_variants_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='sku',
        ),
    ]
