# Generated by Django 5.1.6 on 2026-04-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_flashsale'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='flashsale',
            new_name='product_fla_is_acti_6ead1f_idx',
            old_name='product_fla_is_acti_idx',
        ),
    ]
