# Generated by Django 5.1.6 on 2026-04-25 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_product_fla_is_acti_idx_product_fla_is_acti_6ead1f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='collections/')),
                ('accent_color', models.CharField(default='#212121', help_text='Hex color, e.g. #E53935', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name shown in the header, e.g. Zap, ShoppingBag, Star', max_length=50)),
                ('filter_type', models.CharField(choices=[('manual', 'Manual – hand-picked products'), ('sub_category', 'Sub-category – all products in a sub-category'), ('flash_sale', 'Flash Sale – all live flash-sale products')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='product.product')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='product.sub_category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
