# Generated by Django 5.1.6 on 2025-09-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_clippedcoupon_user_alter_productreview_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='status',
            new_name='published',
        ),
    ]
