# Generated by Django 5.1.6 on 2025-09-23 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_published_productreview_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=36)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='product.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'device_id'], name='product_pro_product_06f53b_idx')],
                'unique_together': {('product', 'device_id')},
            },
        ),
    ]
