# Generated by Django 5.1.6 on 2026-05-15 01:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productviewlog_productdailystats_recentlyviewedproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productview',
            name='product',
        ),
        migrations.RemoveConstraint(
            model_name='productdailystats',
            name='unique_product_daily_stats',
        ),
        migrations.RemoveConstraint(
            model_name='recentlyviewedproduct',
            name='unique_user_recently_viewed',
        ),
        migrations.RenameIndex(
            model_name='productdailystats',
            new_name='product_pro_product_2353db_idx',
            old_name='prod_daily_stats_prod_date_idx',
        ),
        migrations.RenameIndex(
            model_name='productviewlog',
            new_name='product_pro_product_72bf42_idx',
            old_name='prod_view_log_prod_date_idx',
        ),
        migrations.RenameIndex(
            model_name='productviewlog',
            new_name='product_pro_product_8babc2_idx',
            old_name='prod_view_log_bot_date_idx',
        ),
        migrations.RenameIndex(
            model_name='productviewlog',
            new_name='product_pro_visitor_a95510_idx',
            old_name='prod_view_log_visitor_idx',
        ),
        migrations.RenameIndex(
            model_name='recentlyviewedproduct',
            new_name='product_rec_user_id_f06591_idx',
            old_name='recently_viewed_user_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productdailystats',
            unique_together={('product', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='recentlyviewedproduct',
            unique_together={('user', 'product')},
        ),
        migrations.DeleteModel(
            name='ProductView',
        ),
    ]
