# Generated by Django 5.1.6 on 2025-09-23 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['created_at'], name='product_pro_created_230fc0_idx'),
        ),
    ]
