# Generated by Django 5.1.6 on 2025-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_country_name'),
        ('product', '0012_productview_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_in_regions',
            field=models.ManyToManyField(blank=True, related_name='products', to='address.country'),
        ),
    ]
