# Generated by Django 5.1.6 on 2026-08-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productview_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrequentlyBoughtTogether',
        ),
    ]
