# Generated by Django 5.1.6 on 2026-10-07 16:40

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
        ('product', '0013_delete_frequentlyboughttogether'),
        ('vendor', '0009_operations_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('abusive', 'Abusive or offensive'), ('not_about_product', 'Not about this product'), ('fake', 'Suspected fake review'), ('personal_info', 'Contains personal information'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('upheld', 'Upheld (review hidden)'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_sku',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='productreview',
            name='seller_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='seller_replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreview',
            name='seller_reply',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='variants',
            name='seller_sku',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='SKU', unique=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product', 'seller_sku'], name='product_var_product_063749_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('seller_sku', ''), _negated=True), fields=('vendor', 'seller_sku'), name='uniq_product_seller_sku_per_vendor'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='product.productreview'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_reports', to='vendor.vendor'),
        ),
        migrations.AddConstraint(
            model_name='reviewreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('review', 'vendor'), name='uniq_open_review_report_per_vendor'),
        ),
    ]
