# Generated by Django 5.1.6 on 2026-10-07 17:45

import django.db.models.deletion
import product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_seller_sku_review_replies'),
        ('vendor', '0009_operations_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(max_length=255, upload_to=product.models.review_media_path)),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.review_media_path)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Review media',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productreview',
            name='has_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreview',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_verified_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreview',
            name='purchased_variant',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'status', '-helpful_count'], name='review_helpful_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'status', 'has_media'], name='review_media_idx'),
        ),
        migrations.AddField(
            model_name='reviewhelpfulvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='product.productreview'),
        ),
        migrations.AddField(
            model_name='reviewhelpfulvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewmedia',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='product.productreview'),
        ),
        migrations.AddField(
            model_name='reviewmedia',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reviewhelpfulvote',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='uniq_helpful_vote'),
        ),
        migrations.AddIndex(
            model_name='reviewmedia',
            index=models.Index(fields=['review', 'is_hidden', 'position'], name='product_rev_review__714d21_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewmedia',
            index=models.Index(fields=['uploaded_by', 'review', 'created_at'], name='product_rev_uploade_51ab36_idx'),
        ),
    ]
