# Generated by Django 5.1.6 on 2025-09-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_old_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_options',
            field=models.ManyToManyField(related_name='delivery_options', through='product.ProductDeliveryOption', to='product.deliveryoption'),
        ),
    ]
