# Generated by Django 5.1.6 on 2025-10-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
