# Generated by Django 5.1.6 on 2026-10-07 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_backfill_verified_reviews'),
        ('vendor', '0009_operations_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date'], 'permissions': [('moderate_productreview', 'Can moderate product reviews')], 'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.AddField(
            model_name='productreview',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='productreview',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreview',
            name='moderation_flags',
            field=models.JSONField(blank=True, default=list, help_text='Automatic rules that sent this review to manual moderation.'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='moderation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productreview',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='productreview',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='order.orderproduct'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewmoderationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewmoderationevent',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events', to='product.productreview'),
        ),
        migrations.AddIndex(
            model_name='reviewmoderationevent',
            index=models.Index(fields=['review', '-created_at'], name='product_rev_review__30abc4_idx'),
        ),
    ]
