# Generated by Django 5.1.6 on 2025-10-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='type',
            field=models.CharField(choices=[('local', 'Local'), ('international', 'International')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
