# Generated by Django 5.1.6 on 2025-10-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_deliveryoption_provider_deliveryoption_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date',), 'verbose_name_plural': 'products'},
        ),
    ]
