# Generated by Django 5.1.6 on 2025-12-16 12:03

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('order_help', 'Order Assistance'), ('returns', 'Returns & Refunds'), ('wholesale', 'Wholesale / B2B'), ('press', 'Press & Media'), ('partnership', 'Partnership / Influencer'), ('other', 'Other')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', max_length=15)),
                ('admin_note', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('vendor_new_order', 'New Order Received'), ('vendor_order_shipped', 'You Shipped an Order'), ('vendor_order_cancelled', 'Order Cancelled'), ('vendor_payout', 'Payout Processed'), ('vendor_low_stock', 'Low Stock Alert'), ('vendor_new_review', 'New Product Review'), ('vendor_product_approved', 'Product Approved'), ('vendor_product_rejected', 'Product Rejected'), ('vendor_withdrawal_request', 'Withdrawal Requested'), ('vendor_withdrawal_approved', 'Withdrawal Approved'), ('customer_order_placed', 'Order Placed'), ('customer_order_confirmed', 'Order Confirmed'), ('customer_order_shipped', 'Order Shipped'), ('customer_order_delivered', 'Order Delivered'), ('customer_order_cancelled', 'Order Cancelled'), ('customer_refund_processed', 'Refund Processed'), ('customer_tracking_update', 'Tracking Updated'), ('customer_price_drop', 'Price Drop on Watched Item'), ('customer_back_in_stock', 'Item Back in Stock'), ('customer_wishlist_sale', 'Wishlist Item on Sale'), ('customer_review_reminder', 'Please Review Your Purchase'), ('message', 'New Message'), ('announcement', 'Announcement'), ('support_reply', 'Support Ticket Reply'), ('verification_update', 'Account Verification Update'), ('subscription_reminder', 'Subscription Expiring Soon')], max_length=40)),
                ('actor_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('fake', 'Counterfeit / Fake Product'), ('inappropriate', 'Inappropriate Content'), ('spam', 'Spam / Scam'), ('copyright', 'Copyright / Trademark Violation'), ('harassment', 'Harassment or Hate Speech'), ('seller_misconduct', 'Seller Fraud / Misconduct'), ('review_abuse', 'Fake or Abusive Review'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(30)])),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Under Review'), ('valid', 'Action Taken'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=15)),
                ('moderator_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Only visible to staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
