# Generated by Django 5.1.6 on 2025-11-19 11:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('vendor_new_order', 'New Order Received'), ('vendor_order_shipped', 'You Shipped an Order'), ('vendor_order_cancelled', 'Order Cancelled'), ('vendor_payout', 'Payout Processed'), ('vendor_low_stock', 'Low Stock Alert'), ('vendor_new_review', 'New Product Review'), ('vendor_product_approved', 'Product Approved'), ('vendor_product_rejected', 'Product Rejected'), ('vendor_withdrawal_request', 'Withdrawal Requested'), ('vendor_withdrawal_approved', 'Withdrawal Approved'), ('customer_order_placed', 'Order Placed'), ('customer_order_confirmed', 'Order Confirmed'), ('customer_order_shipped', 'Order Shipped'), ('customer_order_delivered', 'Order Delivered'), ('customer_order_cancelled', 'Order Cancelled'), ('customer_refund_processed', 'Refund Processed'), ('customer_tracking_update', 'Tracking Updated'), ('customer_price_drop', 'Price Drop on Watched Item'), ('customer_back_in_stock', 'Item Back in Stock'), ('customer_wishlist_sale', 'Wishlist Item on Sale'), ('customer_review_reminder', 'Please Review Your Purchase'), ('message', 'New Message'), ('announcement', 'Announcement'), ('support_reply', 'Support Ticket Reply'), ('verification_update', 'Account Verification Update'), ('subscription_reminder', 'Subscription Expiring Soon')], max_length=40)),
                ('actor_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_actors', to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a95ed4_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_dd6756_idx'), models.Index(fields=['verb'], name='notificatio_verb_90c7f3_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='notificatio_target__bcda96_idx')],
            },
        ),
    ]
