# Generated by Django 5.1.6 on 2025-11-26 21:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notification', '0001_initial'),
        ('order', '0008_alter_cartitem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('order_help', 'Order Assistance'), ('returns', 'Returns & Refunds'), ('wholesale', 'Wholesale / B2B'), ('press', 'Press & Media'), ('partnership', 'Partnership / Influencer'), ('other', 'Other')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', max_length=15)),
                ('admin_note', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_inquiries', to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('fake', 'Counterfeit / Fake Product'), ('inappropriate', 'Inappropriate Content'), ('spam', 'Spam / Scam'), ('copyright', 'Copyright / Trademark Violation'), ('harassment', 'Harassment or Hate Speech'), ('seller_misconduct', 'Seller Fraud / Misconduct'), ('review_abuse', 'Fake or Abusive Review'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(30)])),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Under Review'), ('valid', 'Action Taken'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=15)),
                ('moderator_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(help_text='What is being reported (Product, Review, Seller, Order, User, etc.)', limit_choices_to={'model__in': ['product', 'vendor', 'order', 'user']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notification.contactinquiry')),
            ],
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['status'], name='contact_inq_status_b7ab91_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['inquiry_type'], name='contact_inq_inquiry_3b13ea_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['created_at'], name='contact_inq_created_0bf0f4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_status_e83c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reason'], name='reports_reason_cd75fc_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='reports_content_0cd725_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_created_c5f642_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'content_type', 'object_id', 'reason'), name='unique_report_per_user_target_reason'),
        ),
    ]
