# Generated by Django 5.1.6 on 2026-05-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('vendor_new_order', 'New Order Received'), ('vendor_order_shipped', 'You Shipped an Order'), ('vendor_order_cancelled', 'Order Cancelled'), ('vendor_payout', 'Payout Processed'), ('vendor_low_stock', 'Low Stock Alert'), ('vendor_new_review', 'New Product Review'), ('vendor_product_approved', 'Product Approved'), ('vendor_product_rejected', 'Product Rejected'), ('vendor_withdrawal_request', 'Withdrawal Requested'), ('vendor_withdrawal_approved', 'Withdrawal Approved'), ('customer_order_placed', 'Order Placed'), ('customer_order_confirmed', 'Order Confirmed'), ('customer_order_shipped', 'Order Shipped'), ('customer_order_delivered', 'Order Delivered'), ('customer_order_cancelled', 'Order Cancelled'), ('customer_refund_processed', 'Refund Processed'), ('customer_tracking_update', 'Tracking Updated'), ('customer_price_drop', 'Price Drop on Watched Item'), ('customer_back_in_stock', 'Item Back in Stock'), ('customer_wishlist_sale', 'Wishlist Item on Sale'), ('customer_review_reminder', 'Please Review Your Purchase'), ('message', 'New Message'), ('announcement', 'Announcement'), ('support_reply', 'Support Ticket Reply'), ('verification_update', 'Account Verification Update'), ('subscription_reminder', 'Subscription Expiring Soon'), ('vendor_inactivity_warning', 'Inactivity Warning'), ('vendor_auto_closed', 'Shop Auto-Closed (Inactivity)'), ('vendor_shop_reopened', 'Shop Reopened')], max_length=40),
        ),
    ]
