# Generated by Django 5.1.6 on 2025-10-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, default='GH', max_length=3, null=True, unique=True),
        ),
    ]
