# Generated by Django 5.1.6 on 2025-10-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='gps_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
