# Generated by Django 5.1.6 on 2026-08-10 22:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0012_alter_productview_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('n_users', models.PositiveIntegerField(default=0)),
                ('n_items', models.PositiveIntegerField(default=0)),
                ('n_interactions', models.PositiveIntegerField(default=0)),
                ('sparsity', models.FloatField(default=0.0, help_text='Fraction of the user×item matrix that is filled')),
                ('factors', models.PositiveSmallIntegerField(default=0)),
                ('iterations', models.PositiveSmallIntegerField(default=0)),
                ('regularization', models.FloatField(default=0.0)),
                ('alpha', models.FloatField(default=0.0, help_text='Implicit-feedback confidence scaling')),
                ('precision_at_10', models.FloatField(blank=True, null=True)),
                ('recall_at_10', models.FloatField(blank=True, null=True)),
                ('map_at_10', models.FloatField(blank=True, null=True)),
                ('ndcg_at_10', models.FloatField(blank=True, null=True)),
                ('catalog_coverage', models.FloatField(blank=True, help_text="Share of the catalog that appears in anyone's top-10", null=True)),
                ('baseline_precision_at_10', models.FloatField(blank=True, help_text='Most-popular baseline — the bar the model must clear', null=True)),
                ('cf_weight', models.FloatField(default=0.0, help_text='0–1. Rises automatically as interaction density grows')),
                ('notes', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Model Run',
                'verbose_name_plural': 'Model Runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-finished_at'], name='rec_run_status_finished_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_vector', models.BinaryField(blank=True, null=True)),
                ('dim', models.PositiveSmallIntegerField(default=0)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('is_cold_start', models.BooleanField(db_index=True, default=True, help_text='Too little history to personalise — serving falls back to trending/deals')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_embeddings', to='recommendation.modelrun')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rec_embedding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Embedding',
                'verbose_name_plural': 'User Embeddings',
            },
        ),
        migrations.CreateModel(
            name='NotInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_interested_by', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='not_interested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Not Interested',
                'verbose_name_plural': 'Not Interested',
                'indexes': [models.Index(fields=['user'], name='rec_notint_user_idx')],
                'unique_together': {('user', 'visitor_key', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductDealScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.FloatField(default=0.0)),
                ('best_price', models.DecimalField(blank=True, decimal_places=2, help_text='Lowest live price in GHS — the flash-sale price when one is running', max_digits=10, null=True)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_remaining', models.PositiveIntegerField(default=0)),
                ('has_flash_sale', models.BooleanField(default=False)),
                ('discount_component', models.FloatField(default=0.0)),
                ('demand_component', models.FloatField(default=0.0)),
                ('quality_component', models.FloatField(default=0.0)),
                ('scarcity_component', models.FloatField(default=0.0)),
                ('freshness_component', models.FloatField(default=0.0)),
                ('price_percentile', models.FloatField(default=1.0, help_text="0–1: where the current price sits in this product's own 30-day range")),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('is_eligible', models.BooleanField(db_index=True, default=False)),
                ('ineligible_reason', models.CharField(blank=True, max_length=100)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_score', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Deal Score',
                'verbose_name_plural': 'Product Deal Scores',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['is_eligible', '-score'], name='rec_deal_serve_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_vector', models.BinaryField(blank=True, null=True)),
                ('content_vector', models.BinaryField(blank=True, null=True)),
                ('dim', models.PositiveSmallIntegerField(default=0, help_text='Width of cf_vector')),
                ('content_dim', models.PositiveSmallIntegerField(default=0, help_text='Width of content_vector')),
                ('interaction_count', models.PositiveIntegerField(default=0, help_text='Weighted interactions behind cf_vector — the confidence in it')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_embeddings', to='recommendation.modelrun')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Embedding',
                'verbose_name_plural': 'Product Embeddings',
                'indexes': [models.Index(fields=['model_run'], name='rec_pemb_run_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductNeighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hybrid', 'Hybrid — blended CF + content'), ('cf', 'Collaborative — co-interaction'), ('content', 'Content — attribute similarity'), ('co_purchase', 'Co-purchase — bought in the same order')], default='hybrid', max_length=15)),
                ('score', models.FloatField(default=0.0)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('support', models.PositiveIntegerField(default=0, help_text='Users/orders behind this pairing — low support means low trust')),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighbors', to='recommendation.modelrun')),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_of', to='product.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Neighbor',
                'verbose_name_plural': 'Product Neighbors',
                'ordering': ['product_id', 'kind', 'rank'],
                'indexes': [models.Index(fields=['product', 'kind', 'rank'], name='rec_nbr_serve_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('product', models.F('neighbor')), _negated=True), name='rec_neighbor_not_self')],
                'unique_together': {('product', 'neighbor', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Price History',
                'verbose_name_plural': 'Product Price History',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['product', '-date'], name='rec_price_hist_idx')],
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(blank=True, db_index=True, help_text='"v:{uuid}" for guests — the same identity scheme as view tracking', max_length=100)),
                ('surface', models.CharField(choices=[('recommended_for_you', 'Recommended for you'), ('todays_deals', "Today's Deals"), ('you_might_also_like', 'You might also like this'), ('customers_also_bought', 'Customers also bought'), ('cart_addons', 'Frequently bought together'), ('keep_shopping', 'Keep shopping for'), ('trending', 'Trending now'), ('search', 'Search results'), ('other', 'Other')], max_length=30)),
                ('event_type', models.CharField(choices=[('impression', 'Impression — rendered in a rail'), ('click', 'Click — opened from a rail'), ('add_to_cart', 'Added to cart from a rail'), ('purchase', 'Purchased after a rail impression')], max_length=15)),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='0-based slot in the rail — needed to debias the ranker', null=True)),
                ('reason', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='recommendation.modelrun')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_events', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Event',
                'verbose_name_plural': 'Recommendation Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['surface', 'event_type', 'date'], name='rec_ev_ctr_idx'), models.Index(fields=['user', '-created_at'], name='rec_ev_user_idx'), models.Index(fields=['product', 'event_type', 'date'], name='rec_ev_product_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(choices=[('recommended_for_you', 'Recommended for you'), ('todays_deals', "Today's Deals"), ('you_might_also_like', 'You might also like this'), ('customers_also_bought', 'Customers also bought'), ('cart_addons', 'Frequently bought together'), ('keep_shopping', 'Keep shopping for'), ('trending', 'Trending now'), ('search', 'Search results'), ('other', 'Other')], default='recommended_for_you', max_length=30)),
                ('score', models.FloatField(default=0.0)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(choices=[('similar_to_viewed', 'Because you viewed'), ('similar_to_bought', 'Because you bought'), ('from_wishlist', 'Based on your wishlist'), ('category_affinity', 'From a category you shop'), ('brand_affinity', 'From a brand you like'), ('collaborative', 'Shoppers like you also bought'), ('deal', 'On deal right now'), ('trending', 'Trending on Negromart'), ('top_rated', 'Highly rated'), ('popular', 'Popular right now')], default='popular', max_length=30)),
                ('reason_detail', models.CharField(blank=True, max_length=200)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='recommendation.modelrun')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='product.product')),
                ('source_product', models.ForeignKey(blank=True, help_text='Seed item this recommendation was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recommendation',
                'verbose_name_plural': 'User Recommendations',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['user', 'surface', 'rank'], name='rec_urec_serve_idx'), models.Index(fields=['generated_at'], name='rec_urec_generated_idx')],
                'unique_together': {('user', 'product', 'surface')},
            },
        ),
    ]
