# Generated by Django 5.1.6 on 2026-08-11 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_delete_frequentlyboughttogether'),
        ('recommendation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notinterested',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='notinterested',
            index=models.Index(fields=['visitor_key', 'product'], name='rec_notint_guest_idx'),
        ),
        migrations.AddConstraint(
            model_name='notinterested',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='rec_notint_unique_user'),
        ),
        migrations.AddConstraint(
            model_name='notinterested',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('visitor_key', 'product'), name='rec_notint_unique_guest'),
        ),
    ]
