# Generated by Django 5.1.6 on 2025-10-16 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_alter_address_gps_address'),
        ('order', '0005_alter_order_total_alter_orderproduct_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.address'),
        ),
    ]
