# Generated by Django 5.1.6 on 2025-11-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='date',
            new_name='created_at',
        ),
    ]
