# Generated by Django 5.1.6 on 2026-04-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cartitem_flash_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='flash_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
