# Generated by Django 5.1.6 on 2025-11-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_date_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('-created_at',)},
        ),
    ]
