# Generated by Django 5.1.6 on 2026-10-07 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cartitem_flash_sale_price'),
        ('vendor', '0009_operations_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('damaged', 'Arrived damaged'), ('defective', 'Does not work / defective'), ('wrong_item', 'Wrong item sent'), ('not_as_described', 'Not as described'), ('missing_parts', 'Missing parts or accessories'), ('changed_mind', 'No longer needed'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, default='', max_length=2000)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved, awaiting return'), ('rejected', 'Rejected'), ('received', 'Item received'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled by customer')], db_index=True, default='requested', max_length=20)),
                ('seller_note', models.TextField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='external_reference',
            field=models.CharField(blank=True, default='', help_text="The courier's own id for this shipment.", max_length=120),
        ),
        migrations.AddField(
            model_name='shipment',
            name='fulfilled_by',
            field=models.CharField(choices=[('platform', 'Negromart delivery'), ('seller', 'Seller delivers'), ('carrier', 'External courier')], default='platform', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='label_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ledger_posted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='provider',
            field=models.CharField(db_index=True, default='platform', max_length=40),
        ),
        migrations.AddField(
            model_name='shipment',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw provider response, kept for support/debugging.'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'ledger_posted_at'], name='shipment_ledger_sweep_idx'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='order.order'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='order.orderproduct'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='return_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='order.shipment'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='vendor.vendor'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['vendor', 'status'], name='order_retur_vendor__40ee54_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['customer', '-created_at'], name='order_retur_custome_e2f5c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('requested', 'approved', 'received'))), fields=('order_product',), name='uniq_open_return_per_order_line'),
        ),
    ]
